version: "3.11"

services:
  patchman:
    image: dalenw/patchman-docker:latest
    depends_on:
      - redis
    volumes:
      - database:/var/lib/patchman/db
    networks:
      - patchman-network
    ports:
      - 8000:8000
    environment:
      ADMIN_EMAIL: admin@example.com
      ADMIN_USERNAME: admin
      ADMIN_PW: password
      TIMEZONE: "America/Denver"
      SECRET_KEY: "${SECRET_KEY}"

  redis:
    image: redis
    networks:
      - patchman-network
    command: [ "redis-server" ]
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 30s
      retries: 3


volumes:
  database:

networks:
  patchman-network:
    driver: overlay